### ISSUE TITLE
Train Function not working

### ISSUE THREAD

**Issue by Ahmad-noborders** [cheripai/en-ja-translator#2]
python train.py
is gibing following error
```
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    train_iters(encoder, decoder, trainloader, validloader, 15, lr=c.LR)
  File "train.py", line 91, in train_iters
    loss = train(input_var, target_var, encoder, decoder, encoder_opt, decoder_opt, criterion, teacher_forcing_ratio=teacher_forcing_ratio, train=True)
  File "train.py", line 39, in train
    encoder_outputs[:, i] = encoder_output
RuntimeError: expand(torch.cuda.FloatTensor{[256, 1, 600]}, size=[256, 600]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)

```
python process_data.py gave this output

`Number of sentences: 139300
Number of trimmed sentences: 127257
Number of en words: 12851
Number of ja words: 16605
Did not find 56 words
Did not find 9507 words
`

**Comment by devsteppe9** [comment]
Hello @Ahmad-noborders 
This error happened to me too. This was a torch version problem. I fixed that below:
1. Download torch package from the site
2. Pip install downloaded package

```
!wget https://download.pytorch.org/whl/cu75/torch-0.2.0.post3-cp36-cp36m-manylinux1_x86_64.whl
!pip install torch-0.2.0.post3-cp36-cp36m-manylinux1_x86_64.whl
```

**Comment by Ahmad-noborders** [comment]
issue fixed 
@Jaha96  thank you so much for your quick support. i really appreciate
